# -*- coding: utf-8 -*-
"""Simple ML Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccFHvmcNEr00gqjtRv3N_MPtCBCwtzSW
"""

print("running")

"""#**Bisnis Understanding**

the sinking of the Titanic is one of the most notorious shipwrecks in the history

#**Load Data**
"""

import pandas as pd
import numpy as np

# prompt: give data from online source

import pandas as pd
import numpy as np
print("running")
# #**Bisnis Understanding**
# the sinking of the Titanic is one of the most notorious shipwrecks in the history
#
#
# #**Load Data**
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
titanic_data = pd.read_csv(url)
titanic_data.head()

# prompt: give me iris dataset

from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
print(iris_df.head())

import numpy as np
from sklearn import datasets

db = datasets.load_diabetes()
db_array=np.array(db.data)

db_array

col = ["age","sex","bmi","bp_avg","s1","s2","s3","s4","s5","s6"]
df_diabetes = pd.DataFrame(data=db_array,columns=col)

df_diabetes

""" craete code for preting data"""